branch-defaults:
  website:
    environment: horse-around-dev
    group_suffix: null
global:
  application_name: horse-around
  branch: null
  default_ec2_keyname: vusal-yeklabs
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: vusal-yeklabs
  repository: null
  sc: git
  workspace_type: Application
